name: ${{ github.ref }}

on:
  release:
    types: [created]

jobs:
  build:
    name: Build Release
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Restore dependencies
      run: dotnet restore CSVToQuery.sln

    - name: Build
      run: dotnet build --configuration Release

    - name: Create Zip Archive
      run: |
        Compress-Archive -Path ./CSVToQuery/bin/Release/net7.0-windows -DestinationPath CSVToQuery_Build.zip
      if: success()

    - name: Publish Release Artifact
      uses: actions/upload-artifact@v2
      with:
        name: WinForms-Release
      
