name: Build on commit to main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0' # Adjust to your desired .NET Framework version
      
    - name: Restore dependencies
      run: nuget restore CSVToQuery.sln
      
    - name: Build solution
      run: '"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin\\MSBuild.exe" /p:Configuration=Release CSVToQuery.sln'
