name: Build on PR to main

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x' # Adjust to your desired .NET Framework version
      
    - name: Restore dependencies
      run: nuget restore YourSolution.sln
      
    - name: Build solution
      run: msbuild /p:Configuration=Release YourSolution.sln
